
version: "3.2"

services:
  subspace:
    build: ./
    image: subspace
    cpu_count: 4
    container_name: subspace
    network_mode: host
    mem_limit: 40000000000
    memswap_limit: 80000000000
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    volumes:
      - ./specs:/subspace/node-subtensor/specs
    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     ./node-subtensor \
    #       --base-path /tmp/blockchain \
    #       --chain ./raw_spec.json \
    #       --rpc-external --rpc-cors all \
    #       --ws-external --no-mdns \
    #       --ws-max-connections 10000 --in-peers 500 --out-peers 500 \
    #       --bootnodes /dns/bootnode.finney.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
    #       --sync warp