[package]
name = "pallet-subspace"
version = "4.0.0-dev"
description = "FRAME pallet for runtime logic of Subspace Blockchain."
authors = ["Commune Nucleus Team"]
homepage = "https://commune.com"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/commune-ai/subspace"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log.workspace = true
ndarray.workspace = true
scale-info.workspace = true
serde_bytes.workspace = true
serde_with.workspace = true
serde-tuple-vec-map.workspace = true
serde.workspace = true

codec.workspace = true
frame-benchmarking = { workspace = true, optional = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-balances.workspace = true
pallet-transaction-payment.workspace = true
sp-arithmetic.workspace = true
sp-core.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
substrate-fixed.workspace = true

[dev-dependencies]
rand.workspace = true
# Substrate
pallet-balances = { workspace = true, features = ["std"] }
parity-util-mem = { workspace = true, features = ['primitive-types'] }
sp-tracing.workspace = true
sp-version.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-std/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
