name: Build and push Docker image

on:
  push:
    branches: [current, feb12]


jobs:
  build-n-push:
    permissions: write-all
    runs-on: ubuntu-22.04-32core-karl
    steps:
    - uses: actions/checkout@v3

    - id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/agicommies/subspace:${{ steps.commit.outputs.short }}
        # , ghcr.io/agicommies/subspace:latest
